main_app/urls.py
# main_app/urls.py

from django.contrib.auth import views as auth_views
from django.contrib.auth.views import LogoutView
from django.urls import path
from . import views
from .views import contact_view, register, profile, new_listings, new_rentals, property_detail, results, property_photos, folder_create, folder_detail, folder_update, listing_toggle_favorite, listing_delete, folder_delete, save_listing, api_property_data_view

urlpatterns = [
    path('', views.home, name='home'),
    # path('', home_view, name='home'),
    path('about/', views.about, name="about"),
    # path('api/realty_data/', realty_data_view, name="realty_data_api"),
    # path('search/', search_view, name="search"),
    path('results/', results, name="results"),
    path('profile/', profile, name="profile"),
    path('error/', views.error, name="error"),
    path('contact/', contact_view, name='contact'),
    # path('login/', CustomLoginView.as_view(), name='login'),
    path('logout/', LogoutView.as_view(next_page='/'), name='logout'),
    path('register/', register, name='register'),
    path('new_listings/', new_listings, name='new_listings'),
    path('new_rentals/', new_rentals, name='new_rentals'),
    path('property/<int:property_id>/', property_detail, name='property_detail'),
    path('property/<int:property_id>/photos/', property_photos, name='property_photos'),
    path('folder/create/', folder_create, name='folder_create'),
    path('folder/<int:folder_id>/', folder_detail, name='folder_detail'),
    path('folder/<int:folder_id>/update/', folder_update, name='folder_update'),
    path('listing/<int:listing_id>/toggle_favorite/', listing_toggle_favorite, name='listing_toggle_favorite'),
    path('listing/<int:listing_id>/delete/', listing_delete, name='listing_delete'),
    path('folder/<int:folder_id>/delete/', folder_delete, name='folder_delete'),
    path('save_listing/<int:folder_id>/', save_listing, name='save_listing'),
    # path('get_listings/', get_listings, name='get_listings'),
    # path('get_property_detail/<str:property_id>/', get_property_detail, name='get_property_detail'),
    # path('api_results/', api_results, name='api_results'),
    # path('api/property_data/', api_property_data_view, name='api_property_data'),

]

realestate/urls.py
# 'realestate/urls.py'

"""
URL configuration for realestate project.

The `urlpatterns` list routes URLs to views. For more information please see:
    https://docs.djangoproject.com/en/5.0/topics/http/urls/
Examples:
Function views
    1. Add an import:  from my_app import views
    2. Add a URL to urlpatterns:  path('', views.home, name='home')
Class-based views
    1. Add an import:  from other_app.views import Home
    2. Add a URL to urlpatterns:  path('', Home.as_view(), name='home')
Including another URLconf
    1. Import the include() function: from django.urls import include, path
    2. Add a URL to urlpatterns:  path('blog/', include('blog.urls'))
"""
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include ('main_app.urls')),
    path('main_app/', include('main_app.urls')),
    path('accounts/', include('django.contrib.auth.urls')),
    path("__reload__/", include("django_browser_reload.urls")),
    
    ]

if settings.DEBUG:
    urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)

main_app/models.py
# main_app/models.py

from django.db import models
from django.urls import reverse
from datetime import date
from django.contrib.auth.models import User  

class Property(models.Model):
    title = models.CharField(max_length=255)
    description = models.TextField()
    address = models.CharField(max_length=255)
    size = models.PositiveIntegerField()
    bedrooms = models.PositiveIntegerField()
    bathrooms = models.PositiveIntegerField()
    price = models.DecimalField(max_digits=10, decimal_places=2)
    status = models.CharField(max_length=50)
    user = models.ForeignKey(User, on_delete=models.CASCADE)

class Rental(models.Model):
    title = models.CharField(max_length=255)
    description = models.TextField()
    address = models.CharField(max_length=255)
    size = models.PositiveIntegerField()
    bedrooms = models.PositiveIntegerField()
    bathrooms = models.PositiveIntegerField()
    price = models.DecimalField(max_digits=10, decimal_places=2)
    status = models.CharField(max_length=50)
    user = models.ForeignKey(User, on_delete=models.CASCADE)

    def __str__(self):
        return self.title

class Transaction(models.Model):
    property = models.ForeignKey(Property, on_delete=models.CASCADE)
    buyer_user = models.ForeignKey(User, related_name='buyer_transactions', on_delete=models.CASCADE)
    seller_agent = models.ForeignKey(User, related_name='seller_transactions', on_delete=models.CASCADE)
    transaction_date = models.DateField()
    amount = models.DecimalField(max_digits=10, decimal_places=2)
    status = models.CharField(max_length=50)

class Listing(models.Model):
    property = models.ForeignKey(Property, on_delete=models.CASCADE)
    folder = models.ForeignKey('Folder', on_delete=models.CASCADE)
    favorite = models.BooleanField(default=False)

class Folder(models.Model):
    name = models.CharField(max_length=255)
    user = models.ForeignKey(User, on_delete=models.CASCADE)

    class Meta:
        permissions = [
            ('can_add_folder', 'Add Folder'),
            ('can_delete_folder', 'Delete Folder'),
            ('can_edit_folder', 'Edit Folder'),
            ('can_view_folder', 'View Folder'),
        ]

    def __str__(self):
        return self.name
    
    
# Define other models such as User, Agent, SearchCriteria, SavedSearch, FavoriteProperty
# Make sure to handle relationships and fields according to your ERD.

main_app/forms.py
# forms.py

from django import forms
from django.contrib.auth.forms import UserCreationForm
from django.core.validators import EmailValidator
from .models import User, Folder

class UserCreationForm(UserCreationForm):
    first_name = forms.CharField(max_length=30, required=True)
    last_name = forms.CharField(max_length=30, required=True)

    class Meta:
        model = User
        fields = UserCreationForm.Meta.fields + ('first_name', 'last_name', 'username', 'email')
        # Add UniqueValidator for username and email
        widgets = {
            'email': forms.EmailInput(attrs={'class': 'form-control'}),
        }
        validators = {
            'email': [EmailValidator(message='This email is already taken.')],
        }
        
class RealtySearchForm(forms.Form):
    min_list_price = forms.DecimalField(label='Minimum List Price', required=False, max_digits=15, decimal_places=2)
    max_list_price = forms.DecimalField(label='Maximum List Price', required=False, max_digits=15, decimal_places=2)
    bedrooms = forms.IntegerField(label='Number of Bedrooms', required=False, min_value=0, max_value=99)
    bathrooms = forms.IntegerField(label='Number of Bathrooms', required=False, min_value=0, max_value=99)

class FolderForm(forms.ModelForm):
    class Meta:
        model = Folder
        fields = ['name']

class FolderCreateForm(forms.ModelForm):
    class Meta:
        model = Folder
        fields = ['name']

class FolderUpdateForm(forms.ModelForm):
    class Meta:
        model = Folder
        fields = ['name']

class SaveListingForm(forms.Form):
    listing_id = forms.CharField(label='Listing ID', max_length=100)

main_app/views.py
# PATH: 'main_app/views.py'

from django.contrib.auth.forms import UserCreationForm
import json
from django.contrib.auth.decorators import login_required
from .forms import UserCreationForm, RealtySearchForm, FolderCreateForm, FolderUpdateForm, SaveListingForm
from django.contrib.auth import login, authenticate
from django.shortcuts import render, redirect, get_object_or_404
from django.http import HttpResponseServerError, JsonResponse
import requests
from .utils import get_access_token, fetch_property_data
from .models import User, Property, Rental, Listing, Folder
from .api_utils import get_dynamic_authorization
from decouple import config

# Create your views here.

def api_property_data_view(request):
    try:
    
    # Access token obtained from the API
        access_token = get_access_token()

    # API endpoint for obtaining property data
        if access_token:
            property_data = fetch_property_data(access_token)
            print(property_data)
        else:
            print("Failed to get access token")

            property_data = None

    except Exception as e:
        print(f"Exception during API call: {e}")
        property_data = None

    # Your existing view code goes here
        
    return render(request, 'main_app/api_results.html', {'property_data': property_data})

def my_view(request):
    x_rapidapi_key = config('X_RAPIDAPI_KEY')

def register(request):
    try:
        if request.method == 'POST':
            form = UserCreationForm(request.POST)
            if form.is_valid():
                user = form.save()
                # user = authenticate(request, firstname=form.cleaned_data['firstname'], lastname=form.cleaned_data['lastname'], password=form.cleaned_data['password1'])
                login(request, user)
                print(f"User authenticated: {request.user}")
                return redirect('profile')
            else:
                print(form.errors)
        else:
            form = UserCreationForm()
        return render(request, 'registration/register.html', {'form': form})
    except Exception as e:
        print(f"Exception during registration: {e}")

def home(request):
    new_listings_data = fetch_new_listings()
    hero_image_urls = [listing['images'][0] for listings in new_listings_data['listings']] if new_listings_data else []
    new_listings = Property.objects.filter(status='For Sale')[:5]
    new_rentals = Rental.objects.filter(status='For Rent')[:5]
    return render(request, 'home.html', {'hero_image_urls': hero_image_urls, 'new_listings_data': new_listings_data, 'new_rentals': new_rentals})
    # return render(request, 'home.html')

@login_required
def profile(request):
    user_folders = Folder.objects.filter(user=request.user)
    return render(request, 'profile.html', {'user_folders': user_folders})

def new_listings(request):
    new_listings = Property.objects.filter(status='For Sale')
    return render(request, 'new_listings.html', {'new_listings': new_listings})

def new_rentals(request):
    new_rentals = Rental.objects.filter(status='For Rent')
    return render(request, 'new_rentals.html', {'new_rentals': new_rentals})

def property_detail(request, property_id):
    property = get_object_or_404(Property, pk=property_id)
    return render(request, 'property_detail.html', {'property': property})

def about(request):
    return render(request, 'about.html')

def search(request):
    return render(request, 'search.html')


def results(request):
    folder_id = request.GET.get('folder_id')
    with open('main_app/static/main_app/json/realty_data.json') as json_file:
        realty_data = json.load(json_file)
    return render(request, 'results.html', {'realty_data': realty_data, 'folder_id': folder_id})

def property_photos(request, property_id):
    property = get_object_or_404(Property, id=property_id)
    return render(request, 'results_photos.html', {'property': property})

    
def error(request):
    return render(request, 'error.html')

def contact_view(request):
    return render(request, 'main_app/contact.html')

@login_required
def folder_create(request):
    if request.method == 'POST':
        form = FolderCreateForm(request.POST)
        if form.is_valid():
            folder = form.save(commit=False)
            folder.user = request.user
            folder.save()
            return redirect('profile')
    else:
        form = FolderCreateForm()
    folder_id = request.GET.get('folder_id')
    return render(request, 'profile.html', {'form': form})

def folder_detail(request, folder_id):
    folder = get_object_or_404(Folder, id=folder_id)
    listings = Listing.objects.filter(folder=folder)
    return render(request, 'folder_detail.html', {'folder': folder, 'listings': listings})

def folder_update(request, folder_id):
    folder = get_object_or_404(Folder, id=folder_id)
    if request.method == 'POST':
        form = FolderUpdateForm(request.POST, instance=folder)
        if form.is_valid():
            form.save()
            return redirect('folder_detail', folder_id=folder.id)
    else:
        form = FolderUpdateForm(instance=folder)
    return render(request, 'folder_update.html', {'folder': folder, 'form': form})

# @login_required
# def save_listing(request):

@login_required
def save_listing(request, folder_id):
    folder = Folder.objects.get(id=folder_id)
    
    if request.method == 'POST':
        form = SaveListingForm(request.POST)
        if form.is_valid():
            listing_id = form.cleaned_data['listing_id']
            save_listing_to_folder(listing_id, folder)
            return redirect('folder_detail', folder_id=folder.id)
    else:
        form = SaveListingForm()

    return render(request, 'save_listing.html', {'form': form, 'folder': folder})




    # if request.method == 'POST':
    #     listing_id = request.POST.get('listing_id')
    #     folder_id = request.POST.get('folder_id')

    #     folder = Folder.objects.get(pk=folder_id) if folder_id else None
        
    #     listing - Listing.objects.get(pk=listing_id)

    #     if folder:
    #         folder.listings.add(listing)
    #     else:
    #         form = FolderCreateForm(request.POST)
    #         if form.is_valid():
    #             new_folder = form.save(commit=False)
    #             new_folder.user = request.user
    #             new_folder.save()
    #             new_folder.listings.add(listing)

    # return redirect('profile')


    #     print(request.POST)
    #     print('Property ID:', property_id)
    #     print('Folder ID:', folder_id)

    #     property = get_object_or_404(Property, id=property_id)
    #     folder = get_object_or_404(Folder, id=folder_id)
    #     Listing.objects.create(property=property, folder=folder)
    #     return redirect('results')  # Redirect to the results page or another page

    # return render(request, 'save_listing.html', {'folders': folders})

def listing_toggle_favorite(request, listing_id):
    listing = get_object_or_404(Listing, id=listing_id)
    listing.favorite = not listing.favorite
    listing.save()
    return redirect('folder_detail', folder_id=listing.folder.id)

def listing_delete(request, folder_id, listing_id):
    SavedListing.objects.filter(folder_id=folder_id, listing_id=listing_id).delete()
    return redirect('folder_detail', folder_id=folder_id)


    # listing = get_object_or_404(Listing, id=listing_id)
    # folder_id = listing.folder.id
    # listing.delete()
    # return redirect('folder_detail', folder_id=folder_id)

def folder_delete(request, folder_id):
    Folder.objects.filter(id=folder_id, user=request.user).delete()
    return redirect('profile')

    # folder = get_object_or_404(Folder, id=folder_id)
    # folder.delete()
    # return redirect('home')  # Adjust the redirection as needed


# def fetch_new_listings():
#     url = "https://mls-router1.p.rapidapi.com/reso/odata/Property"
#     querystring = {"Page": "1", "PageSize": "10", "CultureId": "1"}

#     headers = {
#         "Authorization": "eyJraWQiOiJ4TmlXRnlON1V5OTU5a3hnT3J6ZnJQRGJFdlZDXC8rSGNZQ1RXRlJ1ekJSND0iLCJhbGciOiJSUzI1NiJ9.eyJzdWIiOiIxMThwbzByNmkxbzFjY3N1NmVlNGNsMTMydSIsInRva2VuX3VzZSI6ImFjY2VzcyIsInNjb3BlIjoiYXBpXC9yZWFkIiwiYXV0aF90aW1lIjoxNzA1ODU3NzIwLCJpc3MiOiJodHRwczpcL1wvY29nbml0by1pZHAudXMtZWFzdC0xLmFtYXpvbmF3cy5jb21cL3VzLWVhc3QtMV9Zd0VaemdxdzkiLCJleHAiOjE3MDU4NjEzMjAsImlhdCI6MTcwNTg1NzcyMCwidmVyc2lvbiI6MiwianRpIjoiOTA4OTY5OTgtNTVkMS00ZGRkLWEyOTAtNjJhYjE5ZTgyMjc4IiwiY2xpZW50X2lkIjoiMTE4cG8wcjZpMW8xY2NzdTZlZTRjbDEzMnUifQ.tmJRDagRFd-NFxfIHflheVZxWUFC5XuQPmrAZM0xwMdV4sKfSPB5SxIKLcLJZf8O-9FLokDZhYNx7VPxndbTnc88J_s4ujkunLPdCSbJGCwMQsxLGy_hJdl2Vmz2teRh5D7E9s5itgKjt6qPcUDoixxNsd6U6jrCCbV8TtrLv8UpjBJ9EaeWuoaRjLfFm38xMUFj6-KBRC1snlEqA5xY7udV9FzxXjDlTnLhoGSALrvAMjWKJDf8BbMuw6ayAvTTisEDstXvnJIdlzfGUsOciYiqIkdzHdK-19GmDrVFoV-RBJh04_CUF6oTAq_tubiDJ-uvhRHnh_iXLgokk36XIQ",
#         # "Authorization": f"Bearer {get_dynamic_authorization()}",
#         "x-api-key": "a50YsdAcOQ6xyDqVYTzEB57jBqKVYV01MyTD4at6",
#         "X-RapidAPI-Key": "52d03659f5mshde22d1aee3d427cp1154eajsn60129072a38e",
#         "X-RapidAPI-Host": "mls-router1.p.rapidapi.com",
#     }

#     response = requests.get(url, headers=headers, params=querystring)

#     if response.status_code == 200:
#         return response.json()
#     else:
#         return None


# **********************  API CODE *************************
# Hopefully this is the means of getting the API to work

# def get_listings(request):
#     api_url = "https://api.realtyna.com/mls-router/v1/getListings"

#     headers = {
#         "Content-Type": "application/json",
#         "Authorization": "Bearer YOUR-API-KEY",
#         "x-rapidapi-key": "YOUR-RAPID-API-KEY",
#         "x-rapidapi-host": "mls-router1.p.rapidapi.com",
#     }

#     # Make a request to get listings
#     response = requests.get(api_url, headers=headers)

#     # Process the response
#     if response.status_code == 200:
#         result = response.json()

main_app/templates/about.html
{% extends 'base.html' %}
{% block content %}

<h1 class="text-4xl font-bold">About DW Real Estate</h1>
<hr>
<p>We LOVE Real Estate!</p>


{% endblock %}

main_app/templates/api_results.html
<!-- PATH: 'main_app/templates/api_results.html' -->

{% extends 'base.html' %}
{% block content %}

{% load static %}

<div class="max-w-screen-md mx-auto mt-8">
    <h1 class="text-4xl font-bold text-slate-700">Realty Data Results</h1>

    {% for property in realty_data %}
        <div class="bg-slate-200 p-6 mb-6 rounded-md shadow-md">
            <h2 class="text-2xl font-semibold text-slate-700">{{ property.City }}, {{ property.PostalCode }}</h2>

            <p class="text-slate-500 font-bold mb-2">
                <span class="text-slate-500 mb-2">Price: <span class="text-lg">{{ property.ListPrice }}</span></span>
                <span class="text-slate-500 mb-2">Baths: {{ property.BathroomsTotalInteger }}</span>
                <span class="text-slate-500 mb-2">Beds: {{ property.BedroomsTotal }}</span>
                <span class="text-slate-500 mb-4">Total Sq. Ft.: {{ property.LivingArea }}</span>
            </p>
            <form action="{% url 'save_listing' %}" method="post">
                {% csrf_token %}
                <input type="hidden" name="property_id" value="{{ property.id }}">
                <button type="submit" class="bg-slate-500 hover:bg-slate-700 text-white font-bold py-2 px-4 rounded">
                    Save Listing
                </button>
            </form>

            {% if property.id %}
            <a href="{% url 'property_photos' property.id %}">
                <img src="{{ property.Media.0.MediaURL }}" alt="Property Image" class="w-full h-auto max-h-200 mb-4">
            </a>
            {% else %}
            <img src="{{ property.Media.0.MediaURL }}" alt="Property Image" class="w-full h-auto max-h-200 mb-4">
            {% endif %}

            <p class="text-slate-500">{{ property.PublicRemarks }}</p>

        </div>
    {% endfor %}
</div>

{% endblock %}

main_app/templates/auto_complete_template.html
<!-- auto_complete_template.html -->

<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Auto Complete Results</title>
</head>
<body>
    <h1>Auto Complete Results</h1>
    <pre>{{ data|safe }}</pre>
</body>
</html>

main_app/templates/error.html
<!-- error.html -->

<h1>Error</h1>
<p>{{ error_message }}</p>

main_app/templates/new_listings.html
{% extends 'base.html' %}

{% block content %}
  <h1>New Listings</h1>

  {% for listing in new_listings %}
    <div class="listing">
      <h2>{{ listing.title }}</h2>
      <p>{{ listing.description }}</p>
      <p>Price: ${{ listing.price }}</p>
      <!-- Add more details based on your listing model -->
    </div>
  {% endfor %}

  {% if new_listings.has_other_pages %}
    <span class="pagination">
      <span class="step-links">
          {% if new_listings.has_previous %}
              <a href="?page=new_listings.number-1">&laquo; previous</a>
          {% endif %}
          <span class="current">
              Page {{ new_listings.number }} of {{ new_listings.paginator.num_pages }}.
          </span>
          {% if new_listings.has_next %}
              <a href="?page=new_listings.number+1">next &raquo;</a>
          {% endif %}
      </span>
    </span>
  {% endif %}
{% endblock %}

main_app/templates/profile.html
<!-- main_app/templates/profile.html -->

{% extends 'base.html' %} {% block content %}

<h2 class="text-4xl font-bold md-4 text-slate-700">Profile</h2>

<div class="flex items-center justify-center h-screen text-slate-500">
  <div class="bg-slate-200 shadow-md rounded px-8 pt-6 pb-8 mb-4 max-w-md w-full">
    <h2>Welcome, <span class="text-slate-700 font-bold">{{ user.get_username }}!</span></h2>
    <p>Email: {{ user.email }}</p>
    <p>Joined: {{ user.date_joined }}</p>
    <hr />

    <!-- Folder creation form -->
    <form method="post" action="{% url 'folder_create' %}">
      {% csrf_token %}
      <label for="folder_name">Folder Name:</label>
      <input type="text" id="folder_name" name="folder_name" required />
      <button type="submit" class="font-bold text-slate-700">Create Folder</button>
    </form>

<!-- Display existing folders, if any -->
<h3>Your Folders:</h3>
{% if user.folder_set.all %}
    <ul>
        {% for folder in user.folder_set.all %}
            <li>
                <span class="cursor-pointer hover:underline hover:text-slate-700 hover:font-bold" onclick="toggleFolderContents(this)">
                    {{ folder.name }}
                </span>
                <ul class="folder-contents" style="display: none;">
                    {% for listing in folder.listings.all %}
                        <li>{{ listing.name }}</li>
                    {% endfor %}
                </ul>
            </li>
        {% endfor %}
    </ul>
{% else %}
    <p>No folders yet.</p>
{% endif %}
<script>
    function toggleFolderContents(element) {
        var contents = element.nextElementSibling;
        if (contents.style.display === 'none' || contents.style.display === '') {
            contents.style.display = 'block';
        } else {
            contents.style.display = 'none';
        }
    }
</script>

</div>
</div>

{% endblock %}

main_app/templates/results.html
<!-- PATH: 'main_app/templates/results.html' -->

{% extends 'base.html' %}
{% block content %}

{% load static %}

<div class="max-w-screen-md mx-auto mt-8">
    <h1 class="text-4xl font-bold text-slate-700">Realty Data Results</h1>

    <!-- Display each property from the realty_data array -->
    {% for property in realty_data %}
        <div class="bg-slate-200 p-6 mb-6 rounded-md shadow-md">
            <h2 class="text-2xl font-semibold text-slate-700">{{ property.City }}, {{ property.PostalCode }}</h2>
            <!-- Property details -->
            <p class="text-slate-500 font-bold mb-2">
                <span class="text-slate-500 mb-2">Price: <span class="text-lg">{{ property.ListPrice }}</span></span>
                <span class="text-slate-500 mb-2">Baths: {{ property.BathroomsTotalInteger }}</span>
                <span class="text-slate-500 mb-2">Beds: {{ property.BedroomsTotal }}</span>
                <span class="text-slate-500 mb-4">Total Sq. Ft.: {{ property.LivingArea }}</span>
            </p>
            <!-- Save Listing form -->
            <form action="{% if folder_id %}{% url 'save_listing' folder_id %}{% endif %}" method="post" onsubmit="return showFolderSelectionModal(this);">
                {% csrf_token %}
                <input type="hidden" name="property_id" value="{{ property.id }}">

                <!-- Save Listing button -->
                <button type="submit" class="bg-slate-500 hover:bg-slate-700 text-white font-bold py-2 px-4 rounded">
                    Save Listing
                </button>
            </form>

            <!-- Folder Selection Modal -->
            <div id="folderSelectionModal" class="fixed z-10 inset-0 overflow-y-auto hidden">
                <div class="flex items-end justify-center min-h-screen pt-4 px-4 pb-20 text-center sm:block sm:p-0">
                    <div class="fixed inset-0 transition-opacity" aria-hidden="true">
                        <div class="absolute inset-0 bg-gray-500 opacity-75"></div>
                    </div>

                    <!-- This element is to trick the browser into centering the modal contents. -->
                    <span class="hidden sm:inline-block sm:align-middle sm:h-screen" aria-hidden="true">&#8203;</span>

                    <!-- Modal Content -->
                    <div class="inline-block align-bottom bg-white rounded-lg text-left overflow-hidden shadow-xl transform transition-all sm:my-8 sm:align-middle sm:max-w-lg sm:w-full">
                        <div class="bg-white px-4 pt-5 pb-4 sm:p-6 sm:pb-4">
                            <h3 class="text-lg leading-6 font-medium text-gray-900">Choose folder to save listing to</h3>

                            <!-- Display existing folders, if any -->
                            <ul>
                                {% for folder in user.folder_set.all %}
                                    <li>
                                        <input type="radio" name="folder_id" value="{{ folder.id }}">
                                        <label for="folder_id_{{ folder.id }}" class="cursor-pointer hover:underline hover:text-slate-700 hover:font-bold">
                                            {{ folder.name }}
                                        </label>
                                    </li>
                                {% endfor %}
                            </ul>

                            <!-- Create Folder form -->
                            <label for="new_folder_name">Or create a new folder:</label>
                            <input type="text" id="new_folder_name" name="new_folder_name" />
                        </div>
                        <div class="bg-gray-50 px-4 py-3 sm:px-6 sm:flex sm:flex-row-reverse">
                            <button type="button" onclick="saveListingWithFolder()" class="w-full inline-flex justify-center rounded-md border border-transparent shadow-sm px-4 py-2 bg-slate-500 text-base font-medium text-white hover:bg-slate-700 focus:outline-none focus:ring-2 focus:ring-offset-2 focus:ring-indigo-500 sm:ml-3 sm:w-auto sm:text-sm">
                                Save
                            </button>
                            <button type="button" onclick="hideFolderSelectionModal()" class="mt-3 w-full inline-flex justify-center rounded-md border border-gray-300 shadow-sm px-4 py-2 bg-white text-base font-medium text-gray-700 hover:bg-gray-50 focus:outline-none focus:ring-2 focus:ring-offset-2 focus:ring-indigo-500 sm:mt-0 sm:ml-3 sm:w-auto sm:text-sm">
                                Cancel
                            </button>
                        </div>
                    </div>
                </div>
            </div>

            <!-- Clickable smaller default property image (linked to detailed photos page) -->
            {% if property.id %}
            <a href="{% url 'property_photos' property.id %}">
                <img src="{{ property.Media.0.MediaURL }}" alt="Property Image" class="w-full h-auto max-h-200 mb-4">
            </a>
            {% else %}
            <img src="{{ property.Media.0.MediaURL }}" alt="Property Image" class="w-full h-auto max-h-200 mb-4">
            {% endif %}

            <!-- Add more details as needed -->
            <p class="text-slate-500">{{ property.PublicRemarks }}</p>

        </div>
    {% endfor %}
</div>

<script>
    function showFolderSelectionModal(form) {
        // Display the folder selection modal
        document.getElementById('folderSelectionModal').classList.remove('hidden');

        // Set the form as a global variable so it can be accessed later
        window.currentForm = form;

        // Prevent the default form submission
        return false;
    }

    function hideFolderSelectionModal() {
        // Hide the folder selection modal
        document.getElementById('folderSelectionModal').classList.add('hidden');
    }

    function saveListingWithFolder() {
        // Get the selected folder_id
        var selectedFolderId = document.querySelector('input[name="folder_id"]:checked').value;

        // Set the folder_id value in the original form
        window.currentForm.querySelector('input[name="folder_id"]').value = selectedFolderId;

        // Submit the original form
        window.currentForm.submit();
    }
</script>

{% endblock %}